"use client";
import Head from "next/head";
import Login from "./login/page";
import { ThemeProvider, createTheme } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    mode: "light", // Default to light mode, change to 'dark' if needed
  },
});
export default function Home() {
  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by Create Next App" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-gray-100 min-h-screen">
          <Login />
        </main>
      </ThemeProvider>
    </>
  );
}

// server.js or index.js

// const memoryUsage = process.memoryUsage();

// console.log("Memory Usage at Startup:");
// console.log(`RSS: ${(memoryUsage.rss / 1024 / 1024).toFixed(2)} MB`);
// console.log(
//   `Heap Total: ${(memoryUsage.heapTotal / 1024 / 1024).toFixed(2)} MB`
// );
// console.log(`Heap Used: ${(memoryUsage.heapUsed / 1024 / 1024).toFixed(2)} MB`);
// console.log(`External: ${(memoryUsage.external / 1024 / 1024).toFixed(2)} MB`);
// console.log(
//   `Array Buffers: ${(memoryUsage.arrayBuffers / 1024 / 1024).toFixed(2)} MB`
// );

// Continue with your server setup
